In [1]:
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt
from skimage.measure import compare_psnr
%matplotlib inline

In [2]:
imagePath='1.bmp'
image=cv.imread(imagePath)
image=cv.cvtColor(image,cv.COLOR_BGR2GRAY)
rows,cols=image.shape
rows,cols

(112, 92)

In [3]:
cv.namedWindow('origin', cv.WINDOW_NORMAL)
cv.resizeWindow('origin',300, 300)
cv.imshow('origin',image)
cv.waitKey(0)
cv.destoryAllWindows()


AttributeError: module 'cv2.cv2' has no attribute 'destoryAllWindows'

In [4]:
print("原始图片降维前个数"+str(cols))
print(image)

原始图片降维前个数92
[[126 130 131 ... 121 121 121]
 [128 127 132 ... 121 120 120]
 [129 127 131 ... 120 122 120]
 ...
 [ 47  46  48 ...  34  44  45]
 [ 48  46  44 ...  40  49  41]
 [ 52  46  48 ...  43  51  48]]


In [5]:
mdata=np.float32(np.mat(image))
#去中心化
mean=np.mean(mdata,axis=0)
mmean=np.tile(mean,(rows,1))
newdata=mdata-mmean
newdata.shape

(112, 92)

In [6]:
#找到最大k个特征向量
k=20
covdata=np.cov(newdata,rowvar=0)
D,V=np.linalg.eig(covdata)
eigenvalue=np.argsort(D)
K_eigenvalue=eigenvalue[-1:-(k+1):-1]
K_eigenvector=V[:,K_eigenvalue]

In [7]:
K_eigenvector.shape

(92, 20)

In [8]:
lowdata=newdata*K_eigenvector
lowdata.shape

(112, 20)

In [9]:
fdata=lowdata*K_eigenvector.T+mmean
fdata.shape

(112, 92)

In [10]:
pimage=np.uint8(np.mat(fdata))

cv.namedWindow('1eigen', cv.WINDOW_NORMAL)
cv.resizeWindow('1eigen',300, 300)
cv.imshow('1eigen',pimage)
cv.waitKey(0)
cv.destoryAllWindows()


AttributeError: module 'cv2.cv2' has no attribute 'destoryAllWindows'

In [11]:
print("信噪比",compare_psnr(image,pimage,255))

信噪比 35.323856347958646
